version: "3"

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 8889:3306
    volumes:
      - mysql-base:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
  
  wordpress:
    container_name: wordpress-base
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "9000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db
    volumes:
       - ./wordpress:/var/www/html
       - ./theme:/var/www/html/wp-content/themes/hello-elementor-child
    
volumes:
  mysql-base:

